### ISSUE TITLE
Question, could a tree of data be collaboratively edited using this? 

### ISSUE THREAD

**Issue by PhilAndrew** [d6y/wootjs#10]
Let's say two or more people have a common file system and they do operations such as deleting files, moving files and folders.  This is a tree structure of folders and files. Can this be applied to collaborative editing of file system?

**Comment by d6y** [comment]
Hi @PhilAndrew - I think the general approach of using CRDTs ought to be applicable, but I don't exactly know how.  The group that created WOOT have a paper that looks relevant: http://arxiv.org/abs/1207.5990

Hope that's some help.
