### ISSUE TITLE
Crashes on bulk operations

### ISSUE THREAD

**Issue by lihaoyi** [d6y/wootjs#2]
<img width="1440" alt="screenshot 2015-07-29 09 20 15" src="https://cloud.githubusercontent.com/assets/934140/8963085/0ddb1bde-35d3-11e5-97fc-ed9646fd56fa.png">

To repro:
- Set up locally
- Open two browsers
- To go https://en.wikipedia.org/wiki/Operation_Neptune_(video_game)
- Copy all text
- Paste into one browser
- Watch the browser websocket connection burn

**Comment by d6y** [comment]
Thank you :-)

Paste is mapped in the demo to a series of individual operations, and is horribly slow.  But it shouldn't explode. Thanks for the report. I'll try to make time to investigate.

Is this a FYI for me to improve the demo, or a blocker for you trying to use it? (So I can prioritize)

**Comment by lihaoyi** [comment]
> Is this a FYI for me to improve the demo, or a blocker for you trying to use it? (So I can prioritize)

Both! I'm not 100% sure I'm gonna use it, but if it doesn't work then it's definitely a 0% chance =D And I assume you care about your things working/not-blowing-up so my hope is that I could get some free labour out of you before going into serious-exploration mode myself

**Comment by d6y** [comment]
OK! Ill go do some digging. Looks like weirdness deep in the stack. Do not, I repeat not, hold your breath, but only due to customer work. I want to hack on this.

**Comment by lihaoyi** [comment]
I bet you're missing back-pressure =D

**Comment by d6y** [comment]
Making notes for myself...

```
scala.MatchError: 0 (of class java.lang.Integer)
    at org.http4s.websocket.WebsocketBits$.makeFrame(WebsocketBits.scala:26) ~[http4s-websocket_2.11-0.1.1.jar:0.1.1]
    at org.http4s.websocket.WebsocketBits.makeFrame(WebsocketBits.scala) ~[http4s-websocket_2.11-0.1.1.jar:0.1.1]
    at org.http4s.websocket.FrameTranscoder.bufferToFrame(FrameTranscoder.java:137) ~[http4s-websocket_2.11-0.1.1.jar:0.1.1]
    at org.http4s.blaze.http.websocket.WebSocketDecoder.bufferToMessage(WebSocketDecoder.scala:29) ~[blaze-http_2.11-0.8.2.jar:0.8.2]
```

...gets us to [WebsocketBits.scala](https://github.com/http4s/http4s-websocket/blob/f1d77fd5d12d4dbed6e16486863fc75b3a502c9e/src/main/scala/org/http4s/websocket/WebsocketBits.scala#L26).

Code 0 seems to be continuation according to [rfc6455](http://tools.ietf.org/html/rfc6455)

**Comment by d6y** [comment]
Progress will happen over here:  https://github.com/http4s/http4s-websocket/issues/1

**Comment by d6y** [comment]
Update: PR issued against http4s, we now wait for a merge and build of that project.

**Comment by d6y** [comment]
Bulk operations will still be slow, but the server shouldn't explode any more.

Feel free to re-open the ticket if this doesn't solve the problem.  Thanks!
