### ISSUE TITLE
Can factor out the core as a sperate lib

### ISSUE THREAD

**Issue by sirinath** [d6y/wootjs#3]
Can you factor out the core as a lib where a shared string / data structure is edited by multiple thread?

**Comment by d6y** [comment]
Hi @sirinath - I'm not sure exactly what you need.  The core algorithm in this repository is independent of the web server and Scala.js -- you can use it, and wrap it in whatever concurrency structure you want.

Maybe if you can say what you want to do with it, it might be easier for me to understand what you need.

**Comment by sirinath** [comment]
Looking to see if I can use this as a library.

**Comment by d6y** [comment]
Oh, just as in a published library on Sonatype or Bintray?

**Comment by sirinath** [comment]
Yes

**Comment by d6y** [comment]
OK!

Todos:
- [ ] Extract core algorithm into new project
- [ ] Add publishing configuration, and publsh
- [ ] Add documentation to new project
- [ ] Use published library in this project

**Comment by sirinath** [comment]
Super!
